import i18next from 'i18next';
import { FuseNavigationType } from '@fuse/core/FuseNavigation/types/FuseNavigationType';
import ar from './navigation-i18n/ar';
import en from './navigation-i18n/en';
import tr from './navigation-i18n/tr';

i18next.addResourceBundle('en', 'navigation', en);
i18next.addResourceBundle('tr', 'navigation', tr);
i18next.addResourceBundle('ar', 'navigation', ar);

/**
 * The navigationConfig object is an array of navigation items for the Fuse application.
 */
const navigationConfig: FuseNavigationType = [
  // {
  // 	id: 'example-component',
  // 	title: 'Example',
  // 	translate: 'EXAMPLE',
  // 	type: 'item',
  // 	icon: 'heroicons-outline:star',
  // 	url: 'example',
  // 	auth: ['Admin', 'Customer']
  // },
  {
    id: 'setup',
    title: 'Setup',
    type: 'collapse',
    icon: 'heroicons-outline:cash',
    translate: 'Setup',
    children: [
      {
        id: 'setup-maingroup',
        title: 'Main Group',
        type: 'item',
        url: 'setup/main-group',
        end: true,
      },
      {
        id: 'setup-chartofaccounts',
        title: 'Chart Of Accounts',
        type: 'item',
        url: 'setup/chart-accounts',
        end: true,
      },
      {
        id: 'setup-inventorygroup',
        title: 'Inventory Group',
        type: 'item',
        url: 'setup/inventory-group',
        end: true,
      },
      {
        id: 'setup-inventory',
        title: 'Inventory Information',
        type: 'item',
        url: 'setup/inventory-information',
        end: true,
      },
      {
        id: 'setup-salesmen',
        title: 'Salesmen',
        type: 'item',
        url: 'setup/salesmen',
        end: true,
      },
      {
        id: 'setup-companynames',
        title: 'Company Names',
        type: 'item',
        url: 'setup/company-names',
        end: true,
      },
      {
        id: 'setup-batch',
        title: 'Batch',
        type: 'item',
        url: 'setup/batch',
        end: true,
      },
      {
        id: 'setup-opening-balances',
        title: 'Opening Balances',
        type: 'item',
        url: 'setup/opening-balances',
        end: true,
      },
      {
        id: 'setup-expiry-dates',
        title: 'Expiry Dates',
        type: 'item',
        url: 'setup/expiry-dates',
        end: true,
      },
    ],
  },

  {
    id: 'utilities',
    title: 'Utilities',
    type: 'collapse',
    icon: 'heroicons-outline:menu',
    children: [
      {
        id: 'utilities-newuser',
        title: 'Add New User',
        type: 'item',
        url: 'utilities/new-user',
        end: true,
      },
      {
        id: 'utilities-userlist',
        title: 'All Users',
        type: 'item',
        url: 'utilities/users',
        end: true,
      },
      {
        id: 'utilities-formname',
        title: 'Form Names',
        type: 'item',
        url: 'utilities/form-names',
        end: true,
      },
      {
        id: 'utilities-permissions',
        title: 'Permissions',
        type: 'item',
        url: 'utilities/permissions',
        end: true,
      },
      {
        id: 'utilities-company-info',
        title: 'Company Info',
        type: 'item',
        url: 'utilities/company-info',
        end: true,
      },
      {
        id: 'utilities-opening-balances',
        title: 'Carry Opening Balances',
        type: 'item',
        url: 'utilities/carry-opening-balances',
        end: true,
      },
    ],
  },
  {
    id: 'entry',
    title: 'Entry',
    type: 'collapse',
    icon: 'heroicons-outline:menu',
    children: [
      {
        id: 'entry-salesbill',
        title: 'Sales Bill',
        type: 'item',
        url: 'entry/sales-bill',
        end: true,
      },
      {
        id: 'entry-purchasebill',
        title: 'Purchase Bill',
        type: 'item',
        url: 'entry/purchase-bill',
        end: true,
      },
      {
        id: 'entry-paymentreceipt',
        title: 'Payment Receipt ',
        type: 'item',
        url: 'entry/payment-receipt',
        end: true,
      },
      {
        id: 'entry-estimatebill',
        title: 'Estimate Bill ',
        type: 'item',
        url: 'entry/estimate-bill',
        end: true,
      },
      // {
      //   id: 'entry-salesreturnbill',
      //   title: 'Sales Return Bill',
      //   type: 'item',
      //   url: 'entry/sales-return-bill',
      //   end: true,
      // },
      // {
      //   id: 'entry-purchasereturnbill',
      //   title: 'Purchase Return Bill',
      //   type: 'item',
      //   url: 'entry/purchase-return-bill',
      //   end: true,
      // },
      {
        id: 'entry-generalbill',
        title: 'General Bill',
        type: 'item',
        url: 'entry/general-bill',
        end: true,
      },
     
    ],
  },
  {
    id: 'reports',
    title: 'Reports',
    type: 'collapse',
    icon: 'heroicons-outline:menu',
    children: [
      {
        id: 'one-a/c-head-ledger',
        title: 'One A/C Head Ledger',
        type: 'item',
        url: 'reports/head-ledger',
        end: true,
      },
      {
        id: 'day-book-for-date',
        title: 'Day Book For Date',
        type: 'item',
        url: 'reports/day-book',
        end: true,
      },
      {
        id: 'one-item-ledger',
        title: 'One Item Ledger',
        type: 'item',
        url: 'reports/item-ledger',
        end: true,
      },
      {
        id: 'accounts-reports',
        title: 'Accounts Report',
        type: 'item',
        url: 'reports/accounts-report',
        end: true,
      },     
    ],
  },
  {
  	id: 'dashboards.projects',
  	title: 'Dashboard',
  	type: 'item',
  	icon: 'heroicons-outline:cash',
  	url: '/dashboard',
  	auth: ['Admin'],

  },
  {
    id: 'apps-management',
    title: 'Applications',
    subtitle: 'contacts, chat, documents',
    type: 'group',
    icon: 'heroicons-outline:cash',
    // url: '/dashboards/finance',
    auth: ['Admin'],
    children: [
      {
        id: 'apps-calendar',
        title: 'Calendar',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/apps/calendar',
        auth: ['Admin'],
      },
      {
        id: 'apps-contacts',
        title: 'Contacts',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/apps/contacts',
        auth: ['Admin'],
      },
      {
        id: 'apps-chat',
        title: 'Chat',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/apps/chat',
        auth: ['Admin'],
      },
      // {
      // 	id: 'chat-component',
      // 	title: 'Chat (getstream.io)',
      // 	type: 'item',
      // 	icon: 'heroicons-outline:qrcode',
      // 	url: '/chats',
      // 	auth: ['Admin']

      // },
    ],
  },
  {
    id: 'agent-management',
    title: 'Agent Management',
    subtitle: 'manage agents and payments',
    type: 'group',
    icon: 'heroicons-outline:cash',
    // url: '/dashboards/finance',
    auth: ['Admin'],
    children: [
      {
        id: 'agent-invite-table',
        title: 'Agent Invites',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/agentinvite/table',
        auth: ['Admin'],
      },
      {
        id: 'agent-request-table',
        title: 'Agent Requests',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/agentrequest/table',
        auth: ['Admin'],
      },
      {
        id: 'agents-table',
        title: 'Agents',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/agents/table',
        auth: ['Admin'],
      },
    ],
  },
  {
    id: 'formula-management',
    title: 'Formula Management',
    subtitle: 'manage liqueous formulae',
    type: 'group',
    icon: 'heroicons-outline:cash',
    // url: '/dashboards/finance',
    auth: ['Admin'],
    children: [
      {
        id: 'borro-formula-table',
        title: 'BORRO Formula',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/borroformula/table',
        auth: ['Admin'],
      },
      {
        id: 'block-purchase-formula-table',
        title: 'Block Purchase Formula',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/blockpurchaseformula/table',
        auth: ['Admin'],
      },
      {
        id: 'elc-formula-table',
        title: 'Equity Line Credit Formula',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/elcformula/table',
        auth: ['Admin'],
      },
    ],
  },
  {
    id: 'general-management',
    title: 'General Management',
    subtitle: 'manage user roles and permissions',
    type: 'group',
    icon: 'heroicons-outline:cash',
    // url: '/dashboards/finance',
    auth: null,
    children: [
      {
        id: 'roles-table',
        title: 'Roles',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/roles/table',
        auth: null,
        // ['Admin'],
      },
      {
        id: 'users-table',
        title: 'Admin Users',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/users/table',
        auth: null,
        // ['Admin'],
      },
      {
        id: 'checklist-table',
        title: 'Document Checklist',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/checklist/table',
        auth: null,
        // ['Admin'],
      },
      {
        id: 'labels-table',
        title: 'Labels',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/labels/table',
        auth: ['Admin'],
      },
      {
        id: 'newsletter-table',
        title: 'Newsletter Subscription',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/newsletter/table',
        auth: ['Admin'],
      },
      {
        id: 'contactus-table',
        title: 'Contact Us',
        type: 'item',
        icon: 'heroicons-outline:cash',
        url: '/contactus/table',
        auth: ['Admin'],
      },
    ],
  },
  {
    id: 'notifications',
    title: 'Notifications',
    translate: 'Notifications',
    type: 'item',
    icon: 'heroicons-outline:star',
    url: '/notifications',
    auth: ['Admin', 'Agent', 'Customer'],
  },
];

export default navigationConfig;
